update Dockerfile

diff --git a/materials/Dockerfile b/materials/Dockerfile
--- a/materials/Dockerfile
+++ b/materials/Dockerfile
@@ -1,7 +1,5 @@
-FROM ubuntu:22.04
+FROM debian:stable-slim as build
 
-# Set environment variable to make apt-get install non-interactive
-ENV DEBIAN_FRONTEND=noninteractive
 ENV HOME /root
 
 # Install necessary packages
@@ -18,9 +16,6 @@ RUN apt-get update && \
         libjansson-dev \
         cmake \
         python3 \
-        libevent-dev \
-        libboost-dev \
-        libsqlite3-dev \
         vim \
         nano \
         tmux \
@@ -40,27 +35,42 @@ RUN wget https://github.com/pooler/cpuminer/archive/refs/tags/v2.5.1.tar.gz -O /
     make -j$(nproc) && \
     cp minerd /usr/local/bin/
 
-# Clone and build the Bitcoin fork from source with wallet support
-RUN git clone --branch sv2-tp-0.1.17 https://github.com/Sjors/bitcoin /bitcoin-sv2 && \
-    cd /bitcoin-sv2 && \
-    cmake -B build && \
-    cmake --build build -j $(nproc)
+ENV BITCOIN_RELEASE_TAG=sv2-tp-0.1.17
+ENV BITCOIN_DIR=bitcoin-$BITCOIN_RELEASE_TAG
+
+RUN mkdir -p $BITCOIN_DIR
+
+RUN ARCH=$(dpkg --print-architecture) && \
+    if [ "$ARCH" = "amd64" ]; then \
+        BITCOIN_URL=https://github.com/Sjors/bitcoin/releases/download/$BITCOIN_RELEASE_TAG/bitcoin-$BITCOIN_RELEASE_TAG-x86_64-linux-gnu.tar.gz; \
+    elif [ "$ARCH" = "arm64" ]; then \
+        BITCOIN_URL=https://github.com/Sjors/bitcoin/releases/download/$BITCOIN_RELEASE_TAG/bitcoin-$BITCOIN_RELEASE_TAG-aarch64-linux-gnu.tar.gz; \
+    else \
+        echo "Unsupported architecture"; exit 1; \
+    fi && \
+    wget $BITCOIN_URL -O /tmp/bitcoin.tar.gz
+
+# Extract the downloaded tarball
+RUN tar -xzvf /tmp/bitcoin.tar.gz -C $BITCOIN_DIR --strip-components=1
+
+# Cleanup
+RUN rm /tmp/bitcoin.tar.gz
 
 # Make bitcoin binaries available in $PATH
-RUN ln -s /bitcoin-sv2/build/src/bitcoind /usr/local/bin/bitcoind
-RUN ln -s /bitcoin-sv2/build/src/bitcoin-cli /usr/local/bin/bitcoin-cli
-
+RUN cp $BITCOIN_DIR/bin/bitcoind /usr/local/bin/bitcoind
+RUN cp $BITCOIN_DIR/bin/bitcoin-cli /usr/local/bin/bitcoin-cli
 
 # # Ensure necessary directories are created
 RUN mkdir -p $HOME/.bitcoin-sv2-workshop
+
+ARG CACHE_BUST
+RUN echo "command with external dependencies"
 
 # Clone the Stratum repository, checkout the workshop branch, and build all roles
 RUN cd $HOME && \
     git clone https://github.com/stratum-mining/stratum && \
     cd stratum && \
-    git checkout workshop && \
-    cd roles && \
-    cargo build
+    git checkout workshop
 
 # Copy and run the tmux setup script
 COPY setup-tmux.sh /usr/local/bin/setup-tmux.sh
